<HTML>
<HEAD>
<TITLE>Title</TITLE>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=windows-1251">
<style>
TD   {font-family:Tahoma; font-size:11px;}
A.bot   {font-family:Tahoma;font-size:10;color:#FFFFFF;font:900;padding-left:10px;padding-right:10px;text-decoration:none}
A:hover {color:#000000;} 
.copy   {font-family:Tahoma; font-size:10px; color:5067AF; text-decoration:none; padding-left:10px;  padding-right:10px;}
.terms   {font-family:Tahoma; font-size:10px; color:5067AF; text-decoration:none; padding-left:10px;  padding-right:10px;}
</style>
</HEAD>
<BODY BGCOLOR=#FFFFFF background="images/bg.jpg" text="707070" link="CD1006" vlink="CD1006" alink="CD1006" LEFTMARGIN=0 TOPMARGIN=0 MARGINWIDTH=0 MARGINHEIGHT=0>
<table width="781" border="0" cellpadding="0" cellspacing="0">
  <!--DWLayoutTable-->
  <tr> 
    <TD height="101" COLSPAN=2 valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0">
        <!--DWLayoutTable-->
        <tr> 
          <TD width="235" height="101" valign="top"> <IMG SRC="images/index_01.jpg" ALT=""></TD>
          <TD width="81" valign="top"> <a href="%20"><IMG SRC="images/index_02.jpg" ALT="" border="0"></a></TD>
          <TD width="73" valign="top"> <a href="%20"><IMG SRC="images/index_03.jpg" ALT="" border="0"></a></TD>
          <TD width="80" valign="top"> <a href="%20"><IMG SRC="images/index_04.jpg" ALT="" border="0"></a></TD>
          <TD width="90" valign="top"> <a href="%20"><IMG SRC="images/index_05.jpg" ALT="" border="0"></a></TD>
          <TD width="221" valign="top"> <IMG SRC="images/index_06.jpg" ALT=""></TD>
        </tr>
      </table></TD>
    <td width="1" rowspan="2" valign="top" background="images/111.jpg"><img src="images/111.jpg" width="1" height="1"></td>
  </tr>
  <tr> 
    <TD width="235" height="144" valign="top"> <IMG SRC="images/index_07.jpg" ALT=""></TD>
    <TD width="545" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0" background="images/index_08.jpg">
        <!--DWLayoutTable-->
        <tr> 
          <td width="545" height="144" valign="top" style="padding-top:10px; padding-left:10px; padding-right:10px; padding-bottom:10px"> <font color="#FFFFFF"><img src="images/strelka-3.jpg"> 
            <strong><font color="608AD8">Corporate Website for VOLVO corp</font></strong><br>
            <font color="C1C7D3">Lorem ipsum dolor sit amet, consectetuer adipiscing 
            elit, sed diam nonummy nibh euismod tincidunt ut <br>
            laoreet dolore magna aliquam erat volutpat. <br>
            Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse 
            molestie consequat, vel illum dolore eu <br>
            feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim 
            qui blandit praesent luptatum zzril <br>
            delenit augue duis dolore te feugait nulla facilisi.</font></font><br><br>
            <a href="%20"><img src="images/more-info-top.jpg" border="0"></a></td>
        </tr>
      </table></TD>
  </tr>
</table>
<table width="781" border="0" cellpadding="0" cellspacing="0">
  <!--DWLayoutTable-->
  <tr> 
    <td width="27" height="10"></td>
    <td width="228"></td>
    <td width="22"></td>
    <td width="228"></td>
    <td width="22"></td>
    <td width="228"></td>
    <td width="25"></td>
    <td width="1" rowspan="2" valign="top" background="images/111.jpg"><img src="images/111.jpg" width="1" height="1"></td>
  </tr>
  <tr> 
    <td height="333">&nbsp;</td>
    <td valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
        <!--DWLayoutTable-->
        <tr> 
          <td height="21" colspan="3" valign="top"><img src="images/co-casher-53_12.jpg"></td>
        </tr>
        <tr> 
          <td width="11" height="303">&nbsp;</td>
          <td width="208" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0">
              <!--DWLayoutTable-->
              <tr> 
                <td width="208" height="80" valign="top" style="padding-bottom:5px; padding-top:10px"><img src="images/strelka-2.jpg"> 
                  <strong><font color="253556">Lorem ipsum dolor</font></strong><br>
                  sit amet, consectetuer adipiscing elit, sed diam nonummy nibh 
                  euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</td>
              </tr>
              <tr> 
                <td height="36" valign="top" bgcolor="E9EAEE" style="padding-top:5px; padding-bottom:5px; padding-left:5px; padding-right:5px"><img src="images/strelka.jpg"> 
                  <a href="%20">Volvo corp. web-site</a><br> <img src="images/strelka.jpg"> 
                  <a href="%20">Mercedes Benz promo site </a></td>
              </tr>
              <tr> 
                <td height="187" valign="top" style="padding-bottom:5px; padding-top:10px"><img src="images/razdel-1.jpg"><br> 
                  <img src="images/picture-001.jpg"><br>
                  Duis autem vel eum iriure dolor in hendrerit <br>
                  in vulputate velit esse molestie consequat, <br>
                  vel illum dolore eu feugiat.</td>
              </tr>
            </table></td>
          <td width="9">&nbsp;</td>
        </tr>
        <tr> 
          <td height="9"></td>
          <td></td>
          <td></td>
        </tr>
      </table></td>
    <td>&nbsp;</td>
    <td valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
        <!--DWLayoutTable-->
        <tr> 
          <td height="21" colspan="3" valign="top"><img src="images/co-casher-53_14.jpg"></td>
        </tr>
        <tr> 
          <td width="11" height="245">&nbsp;</td>
          <td width="206" valign="top" style="padding-bottom:10px"><img src="images/picture-002.jpg"><br> 
            <strong><font color="253556">Case Solutions</font></strong><br>
            Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse 
            molestie consequat, vel illum dolore eu feugiat nulla facilisis at 
            vero eros et accumsan et iusto odio dignissim qui blandit praesent 
            luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</td>
          <td width="11">&nbsp;</td>
        </tr>
        <tr> 
          <td height="36">&nbsp;</td>
          <td height="36" valign="top" bgcolor="E9EAEE" style="padding-top:5px; padding-bottom:5px; padding-left:5px; padding-right:5px"><img src="images/strelka.jpg"> 
            <a href="%20">Volvo corp. web-site</a><br> <img src="images/strelka.jpg"> 
            <a href="%20">Mercedes Benz promo site </a></td>
          <td>&nbsp;</td>
        </tr>
        <tr> 
          <td height="31">&nbsp;</td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
      </table></td>
    <td>&nbsp;</td>
    <td valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
        <!--DWLayoutTable-->
        <tr> 
          <td width="228" height="21" valign="top"><img src="images/co-casher-53_16.jpg"></td>
        </tr>
        <tr> 
          <td height="119" valign="top" style="padding-bottom:5px; padding-top:10px; padding-left:10px; padding-right:10px"> 
            <font color="253556"><strong><img src="images/strelka-2.jpg">Friday, 
            13 november 2003</strong></font><br>
            Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse 
            molestie consequat, vel illum dolore eu feugiat nulla facilisis at 
            vero eros et accumsan et iusto odio dignissim qui blandit praesent 
            luptatum zzril delenit augue duis dolore te feugait nulla facilisi. 
          </td>
        </tr>
        <tr> 
          <td height="37" valign="top"><a href="%20"><img src="images/more-info.jpg" border="0"></a></td>
        </tr>
        <tr> 
          <td height="119" valign="top" style="padding-bottom:5px; padding-top:10px; padding-left:10px; padding-right:10px"> 
            <font color="#000000"><strong><img src="images/strelka-2.jpg"><font color="253556">Friday, 
            13 november 2003</font></strong></font><br>
            Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse 
            molestie consequat, vel illum dolore eu feugiat nulla facilisis at 
            vero eros et accumsan et iusto odio dignissim qui blandit praesent 
            luptatum zzril delenit augue duis dolore te feugait nulla facilisi. 
          </td>
          </tr>
        <tr> 
          <td height="37" valign="top"><a href="%20"><img src="images/more-info.jpg" border="0"></a></td>
        </tr>
      </table></td>
    <td>&nbsp;</td>
  </tr>
</table>
<table width="781" border="0" cellpadding="0" cellspacing="0">
  <!--DWLayoutTable-->
  <tr> 
    <td width="780" height="65" align="center" valign="middle"><img src="images/copyright.jpg">
<div style="text-align:center;font-family:Arial,Helvetica,Sans-Serif;font-size:11px;color:#fff;"><a style="text-decoration:none;color:#fff;" href="http://www.quackit.com">Tutorials</a> | <a style="text-decoration:none;color:#fff;" href="http://www.htmlcodes.me">Codes</a> | <a style="text-decoration:none;color:#fff;" href="http://www.free-templates.me">Templates</a></div>

	</td>
    <td width="1" valign="top" background="images/111.jpg"><img src="images/111.jpg" width="1" height="1"></td>
  </tr>
  <tr> 
    <td height="1" colspan="2" valign="top" background="images/111.jpg"><img src="images/111.jpg" width="1" height="1"></td>
  </tr>
</table>
</BODY>
</HTML>